<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17767" started-at="2018-06-05T04:49:48Z" finished-at="2018-06-05T04:50:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17767" started-at="2018-06-05T04:49:48Z" finished-at="2018-06-05T04:50:06Z">
      <class name="com.myntra.testframework.testcases.HomePageTestCases">
        <test-method status="PASS" signature="beforeTestCase()[pri:0, instance:com.myntra.testframework.testcases.HomePageTestCases@548a9f61]" name="beforeTestCase" is-config="true" duration-ms="6077" started-at="2018-06-05T10:19:48Z" finished-at="2018-06-05T10:19:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestCase -->
        <test-method status="PASS" signature="beforeTestmethod()[pri:0, instance:com.myntra.testframework.testcases.HomePageTestCases@548a9f61]" name="beforeTestmethod" is-config="true" duration-ms="7245" started-at="2018-06-05T10:19:54Z" finished-at="2018-06-05T10:20:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestmethod -->
        <test-method status="FAIL" signature="tabsPresentOrNot()[pri:0, instance:com.myntra.testframework.testcases.HomePageTestCases@548a9f61]" name="tabsPresentOrNot" duration-ms="636" started-at="2018-06-05T10:20:02Z" finished-at="2018-06-05T10:20:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [Kids]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [Kids]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.myntra.testframework.testcases.HomePageTestCases.tabsPresentOrNot(HomePageTestCases.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tabsPresentOrNot -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.myntra.testframework.testcases.HomePageTestCases@548a9f61]" name="afterMethod" is-config="true" duration-ms="3773" started-at="2018-06-05T10:20:02Z" finished-at="2018-06-05T10:20:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=tabsPresentOrNot status=FAILURE method=HomePageTestCases.tabsPresentOrNot()[pri:0, instance:com.myntra.testframework.testcases.HomePageTestCases@548a9f61] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.myntra.testframework.testcases.HomePageTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
